apiVersion: v1
kind: Service
metadata:
  name: consumidor-twitches-svc
  labels:
    app: consumidor-twitches
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: consumidor-twitches
  
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-api-kafka-svc
  labels:
    app: twitter-api-kafka
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: twitter-api-kafka